In [2]:
import pandas as pd
import numpy as np
import os

pd.set_option("display.max_columns", None)     # don't coalesce columns when viewing output
pd.set_option("display.max_rows", None)        # don't coalesce rows when viewing output
# pd.set_option('display.max_colwidth', None)  # to see all the data in a column

In [3]:
os.listdir("./large_data/scania/data/")

['test_labels.csv',
 'test_operational_readouts.csv',
 'test_specifications.csv',
 'train_operational_readouts.csv',
 'train_specifications.csv',
 'train_tte.csv',
 'validation_labels.csv',
 'validation_operational_readouts.csv',
 'validation_specifications.csv']

In [11]:
df2 = pd.read_csv("./large_data/scania/data/validation_operational_readouts.csv")
df2.shape

(196227, 107)

In [12]:
df2.head()

,vehicle_id,time_step,171_0,666_0,427_0,837_0,167_0,167_1,167_2,167_3,167_4,167_5,167_6,167_7,167_8,167_9,309_0,272_0,272_1,272_2,272_3,272_4,272_5,272_6,272_7,272_8,272_9,835_0,370_0,291_0,291_1,291_2,291_3,291_4,291_5,291_6,291_7,291_8,291_9,291_10,158_0,158_1,158_2,158_3,158_4,158_5,158_6,158_7,158_8,158_9,100_0,459_0,459_1,459_2,459_3,459_4,459_5,459_6,459_7,459_8,459_9,459_10,459_11,459_12,459_13,459_14,459_15,459_16,459_17,459_18,459_19,397_0,397_1,397_2,397_3,397_4,397_5,397_6,397_7,397_8,397_9,397_10,397_11,397_12,397_13,397_14,397_15,397_16,397_17,397_18,397_19,397_20,397_21,397_22,397_23,397_24,397_25,397_26,397_27,397_28,397_29,397_30,397_31,397_32,397_33,397_34,397_35
0,10,3.0,46590.0,3696.0,2038959.0,1450.0,0.0,273826.0,339584.0,99834.0,250922.0,1411788.0,357113.0,27034.0,2198.0,0.0,70.0,44098.0,26120.0,12900.0,20960.0,279122.0,12725.0,124.0,0.0,0.0,0.0,2071653.0,0.0,712.0,320.0,353.0,569.0,208.0,48.0,177.0,192.0,120.0,248.0,80.0,21240.0,430191.0,546048.0,166546.0,149355.0,110700.0,83556.0,69345.0,106236.0,99001.0,165052.0,120.700139,40.085208,47.315069,63.458750,77.539236,88.971319,103.708056,123.059583,276.914306,342.500694,217.659722,305.552847,354.001042,604.575694,1479.010764,1283.698611,406.370972,0.191319,0.000000,0.005625,344190.0,249270.0,226995.0,12510.0,11610.0,2040.0,450781.0,134895.0,368565.0,7065.0,1261.0,30.0,27616.0,115141.0,242972.0,7380.0,1696.0,30.0,9181.0,93511.0,141781.0,7187.0,1110.0,15.0,6496.0,74880.0,100725.0,8026.0,855.0,15.0,495.0,91665.0,169125.0,51900.0,9362.0,0.0
1,10,7.4,127110.0,16716.0,6501456.0,4660.0,0.0,635642.0,609742.0,288036.0,781775.0,4592210.0,1715785.0,82866.0,2198.0,0.0,70.0,106579.0,46710.0,27098.0,56310.0,954252.0,57347.0,124.0,0.0,0.0,0.0,6530228.0,0.0,1648.0,664.0,689.0,1601.0,801.0,409.0,809.0,824.0,1041.0,1488.0,136.0,54936.0,1384740.0,1626471.0,450964.0,410724.0,344925.0,268488.0,232686.0,438867.0,405307.0,496081.0,344.130486,216.756250,324.007569,432.727222,518.133264,589.343333,641.517083,706.043542,1670.332778,1645.494792,1035.262361,1409.725069,1553.562014,2520.997153,4089.285139,1881.583194,443.728542,0.384444,0.010972,0.006667,1259850.0,1042830.0,718113.0,88172.0,85561.0,15570.0,1180141.0,429137.0,612150.0,37126.0,9346.0,616.0,97877.0,382653.0,501799.0,45165.0,12722.0,345.0,39304.0,320401.0,395162.0,48348.0,9840.0,345.0,25368.0,229531.0,295291.0,44312.0,7995.0,75.0,2265.0,414180.0,688891.0,258810.0,63167.0,1005.0
2,10,8.0,144015.0,19596.0,7327918.0,5230.0,0.0,654780.0,665756.0,300174.0,836039.0,5109160.0,2067521.0,100184.0,2198.0,0.0,70.0,109854.0,50894.0,29612.0,61306.0,1080604.0,63359.0,124.0,0.0,0.0,0.0,7301186.0,0.0,1736.0,688.0,745.0,1753.0,818.0,417.0,857.0,872.0,1169.0,1720.0,152.0,62064.0,1529361.0,1784754.0,491284.0,455994.0,387576.0,306828.0,267210.0,510417.0,485389.0,537817.0,367.498333,235.925972,352.601319,470.515278,571.397500,657.484097,723.373472,793.152431,1922.070833,1928.429792,1223.466389,1682.178958,1887.363958,2904.826597,4605.936458,2142.888542,473.712986,0.621667,0.058333,0.008472,1462831.0,1160565.0,801858.0,102558.0,96211.0,19351.0,1226987.0,468723.0,640155.0,41372.0,10576.0,751.0,105692.0,435138.0,539419.0,49711.0,14208.0,375.0,43144.0,370261.0,434463.0,54739.0,11010.0,375.0,28173.0,271081.0,335479.0,52203.0,9421.0,75.0,2415.0,487080.0,812071.0,300735.0,77477.0,1500.0
3,10,12.0,187560.0,24264.0,9286082.0,7420.0,2647.0,831628.0,794332.0,360066.0,955781.0,6172908.0,2799091.0,240002.0,10864.0,0.0,77.0,138006.0,64908.0,34672.0,69648.0,1346750.0,90503.0,528.0,0.0,0.0,0.0,9128870.0,0.0,2081.0,816.0,945.0,2113.0,1026.0,458.0,905.0,944.0,1337.0,1872.0,248.0,89406.0,1862604.0,2175282.0,577037.0,559746.0,486351.0,396810.0,344934.0,667206.0,693181.0,634061.0,433.936667,276.401389,399.583472,530.232500,634.750625,798.893889,866.071389,1030.670278,2402.546944,2533.728056,1607.636458,2230.352778,2531.052778,3608.536806,6521.322847,2875.241458,504.678889,0.625556,0.058333,0.008472,1890256.0,1409880.0,1033338.0,118353.0,121159.0,47431.0,1378562.0,532788.0,758476.0,48468.0,12136.0,886.0,128462.0,485778.0,713749.0,57466.0,16460.0,420.0,53539.0,425612.0,606859.0,62557.0,12946.0,375.0,33513.0,321694.0,463265.0,61399.0,10727.0,75.0,2610.0,655620.0,1118116.0,403516.0,99587.0,1591.0
4,10,12.2,187575.0,24264.0,9286082.0,7420.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,77.0,138006.0,64908.0,34672.0,69648.0,1346750.0,90504.0,528.0,0.0,0.0,0.0,9128870.0,0.0,2081.0,816.0,945.0,2113.0,1026.0,458.0,905.0,945.0,1338.0,1872.0,249.0,89406.0,1862605.0,2175282.0,577037.0,559747.0,486351.0,396810.0,344934.0,667206.0,693182.0,634062.0,434.936667,276.401389,399.583472,530.232500,634.750625,798.893889,866.071389,1030.670278,2402.546944,2533.728056,1607.636458,2230.352778,2531.052778,3609.536806,6522.322847,2875.241458,505.678889,0.625556,0.058333,0.008472,1890256.0,1409880.0,1033339.0,118355.0,121159.0,47431.0,1378562.0,532788.0,758478.0,48470.0,12137.0,886.0,128462.0,485778.0,713749.0,57467.0,16460.0,420.0,53539.0,425612.0,606860.0,62558.0,12946.0,375.0,33514.0,321694.0,463265.0,61400.0,10727.0,75.0,2611.0,655620.0,1118116.0,403517.0,99588.0,1592.0

In [13]:
list(df2.columns)

['vehicle_id',
 'time_step',
 '171_0',
 '666_0',
 '427_0',
 '837_0',
 '167_0',
 '167_1',
 '167_2',
 '167_3',
 '167_4',
 '167_5',
 '167_6',
 '167_7',
 '167_8',
 '167_9',
 '309_0',
 '272_0',
 '272_1',
 '272_2',
 '272_3',
 '272_4',
 '272_5',
 '272_6',
 '272_7',
 '272_8',
 '272_9',
 '835_0',
 '370_0',
 '291_0',
 '291_1',
 '291_2',
 '291_3',
 '291_4',
 '291_5',
 '291_6',
 '291_7',
 '291_8',
 '291_9',
 '291_10',
 '158_0',
 '158_1',
 '158_2',
 '158_3',
 '158_4',
 '158_5',
 '158_6',
 '158_7',
 '158_8',
 '158_9',
 '100_0',
 '459_0',
 '459_1',
 '459_2',
 '459_3',
 '459_4',
 '459_5',
 '459_6',
 '459_7',
 '459_8',
 '459_9',
 '459_10',
 '459_11',
 '459_12',
 '459_13',
 '459_14',
 '459_15',
 '459_16',
 '459_17',
 '459_18',
 '459_19',
 '397_0',
 '397_1',
 '397_2',
 '397_3',
 '397_4',
 '397_5',
 '397_6',
 '397_7',
 '397_8',
 '397_9',
 '397_10',
 '397_11',
 '397_12',
 '397_13',
 '397_14',
 '397_15',
 '397_16',
 '397_17',
 '397_18',
 '397_19',
 '397_20',
 '397_21',
 '397_22',
 '397_23',
 '397_24',
 '397_25',
 '397_26',
 '397_27',
 '397_28',
 '397_29',
 '397_30',
 '397_31',
 '397_32',
 '397_33',
 '397_34',
 '397_35']

In [4]:
df = pd.read_csv("./large_data/scania/data/train_operational_readouts.csv")
df.shape

(1122452, 107)

In [6]:
list(df.columns)

['vehicle_id',
 'time_step',
 '171_0',
 '666_0',
 '427_0',
 '837_0',
 '167_0',
 '167_1',
 '167_2',
 '167_3',
 '167_4',
 '167_5',
 '167_6',
 '167_7',
 '167_8',
 '167_9',
 '309_0',
 '272_0',
 '272_1',
 '272_2',
 '272_3',
 '272_4',
 '272_5',
 '272_6',
 '272_7',
 '272_8',
 '272_9',
 '835_0',
 '370_0',
 '291_0',
 '291_1',
 '291_2',
 '291_3',
 '291_4',
 '291_5',
 '291_6',
 '291_7',
 '291_8',
 '291_9',
 '291_10',
 '158_0',
 '158_1',
 '158_2',
 '158_3',
 '158_4',
 '158_5',
 '158_6',
 '158_7',
 '158_8',
 '158_9',
 '100_0',
 '459_0',
 '459_1',
 '459_2',
 '459_3',
 '459_4',
 '459_5',
 '459_6',
 '459_7',
 '459_8',
 '459_9',
 '459_10',
 '459_11',
 '459_12',
 '459_13',
 '459_14',
 '459_15',
 '459_16',
 '459_17',
 '459_18',
 '459_19',
 '397_0',
 '397_1',
 '397_2',
 '397_3',
 '397_4',
 '397_5',
 '397_6',
 '397_7',
 '397_8',
 '397_9',
 '397_10',
 '397_11',
 '397_12',
 '397_13',
 '397_14',
 '397_15',
 '397_16',
 '397_17',
 '397_18',
 '397_19',
 '397_20',
 '397_21',
 '397_22',
 '397_23',
 '397_24',
 '397_25',
 '397_26',
 '397_27',
 '397_28',
 '397_29',
 '397_30',
 '397_31',
 '397_32',
 '397_33',
 '397_34',
 '397_35']

In [5]:
df.head(3)

,vehicle_id,time_step,171_0,666_0,427_0,837_0,167_0,167_1,167_2,167_3,167_4,167_5,167_6,167_7,167_8,167_9,309_0,272_0,272_1,272_2,272_3,272_4,272_5,272_6,272_7,272_8,272_9,835_0,370_0,291_0,291_1,291_2,291_3,291_4,291_5,291_6,291_7,291_8,291_9,291_10,158_0,158_1,158_2,158_3,158_4,158_5,158_6,158_7,158_8,158_9,100_0,459_0,459_1,459_2,459_3,459_4,459_5,459_6,459_7,459_8,459_9,459_10,459_11,459_12,459_13,459_14,459_15,459_16,459_17,459_18,459_19,397_0,397_1,397_2,397_3,397_4,397_5,397_6,397_7,397_8,397_9,397_10,397_11,397_12,397_13,397_14,397_15,397_16,397_17,397_18,397_19,397_20,397_21,397_22,397_23,397_24,397_25,397_26,397_27,397_28,397_29,397_30,397_31,397_32,397_33,397_34,397_35
0,0,11.2,167985.0,10787.0,7413813.0,2296.0,4110.0,1296420.0,1628265.0,630345.0,1269525.0,4772940.0,2706706.0,222225.0,6240.0,0.0,70.0,1435083.0,857662.0,384579.0,668642.0,7239843.0,398490.0,3887.0,0.0,0.0,0.0,8036751.0,0.0,1227.0,555.0,463.0,925.0,468.0,225.0,535.0,516.0,492.0,729.0,66.0,97056.0,2690052.0,2945268.0,788437.0,687480.0,595164.0,491232.0,532932.0,809628.0,505693.0,858410.0,203.676778,111.91150,147.265389,200.479944,230.306278,277.722417,315.748806,372.164528,864.246250,920.881111,637.901639,744.618944,880.866889,1272.323972,1847.623667,940.785694,2.900083,0.208444,0.056417,0.058444,446956.0,411420.0,203024.0,26636.0,29156.0,7616.0,449537.0,233352.0,139920.0,12648.0,2813.0,224.0,53161.0,178881.0,138250.0,13328.0,3581.0,88.0,16361.0,131601.0,116541.0,13506.0,2856.0,48.0,6337.0,105412.0,95728.0,15609.0,1984.0,8.0,784.0,150228.0,261904.0,93172.0,17874.0,452.0
1,0,11.4,167985.0,10787.0,7413813.0,2296.0,4111.0,1302855.0,1628265.0,630345.0,1269526.0,4772940.0,2706706.0,222225.0,6240.0,0.0,70.0,1440661.0,857662.0,384579.0,668642.0,7239843.0,398490.0,3887.0,0.0,0.0,0.0,8040811.0,0.0,1230.0,558.0,463.0,925.0,469.0,226.0,535.0,516.0,493.0,729.0,66.0,97056.0,2693100.0,2947368.0,788437.0,687480.0,595164.0,491232.0,532932.0,809628.0,505693.0,860571.0,204.256750,112.92425,147.265389,201.479944,230.306278,277.722417,315.748806,372.164528,864.246250,920.881111,637.901639,745.618944,880.866889,1272.323972,1847.623667,940.785694,2.900083,0.208444,0.056417,0.058444,446964.0,411420.0,203027.0,26638.0,29157.0,7616.0,451193.0,233354.0,139920.0,12649.0,2813.0,224.0,53210.0,178883.0,138252.0,13328.0,3582.0,88.0,16368.0,131601.0,116542.0,13507.0,2856.0,48.0,6339.0,105413.0,95729.0,15610.0,1984.0,8.0,784.0,150228.0,261905.0,93172.0,17874.0,452.0
2,0,19.6,331635.0,14525.0,13683604.0,2600.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,70.0,1787736.0,1133132.0,598351.0,1167062.0,12314224.0,460240.0,3887.0,0.0,0.0,0.0,12777022.0,0.0,2136.0,954.0,850.0,1420.0,722.0,412.0,880.0,666.0,586.0,1143.0,162.0,181632.0,4249020.0,4630440.0,1539133.0,1421172.0,1039764.0,749472.0,740724.0,995796.0,574045.0,1379191.0,321.671972,157.31250,193.792833,263.577611,310.711861,366.149250,415.642472,484.391167,1146.111611,1286.536333,900.062917,1123.232556,1449.545611,2140.037472,5046.748278,1151.010139,3.320194,0.218806,0.056778,0.058444,756665.0,647348.0,286811.0,30967.0,31213.0,7745.0,633790.0,423395.0,271940.0,16190.0,3573.0,232.0,75038.0,352791.0,327992.0,17325.0,4451.0,92.0,24028.0,234737.0,216619.0,17000.0,3476.0,48.0,12055.0,167693.0,142900.0,19263.0,2441.0,12.0,1420.0,204832.0,313485.0,106464.0,19306.0,452.0